name : Terraform 

on: 
  push :
    branches: [main]
  
jobs:
   Terraform init validate plan and apply:
     name: eks run using Terraform
     runs-on: Ubuntu-latest

   steps:
     -  name : checkout
        uses : action/checkout@v4
     -  name : install Terraform 
        uses: hashicorp/setup-terraform@v3
        with:
           terraform_version: "1.1.7"
     -  name : install aws cli 
        uses: aws-actions/configure-aws-credentials@v2
        with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1 
     - name : execute terraform init
       run : terraform init
       workingdirectory: MINI PROJECT
     - name : execute terraform validate
       run : terraform validate
       workingdirectory: MINI PROJECT
     - name : execute terraform plan 
       run : terraform plan -var-file= "terraform.tfvars"
       workingdirectory: MINI PROJECT
     - name : execute terraform apply 
       run : terrafotm apply -var-file ="terraform.tfvars""
       workingdirectory: MINI PROJECT
       environment: 
        name : production 


  
    
         
         





    