name : Docker build

on: 
  push:
    branches: 
      - master
    workflow_dispatch:    

jobs: 
  Docker build push and deploy :
   name: Docker platform
   runs-on: Ubuntu-latest
  steps:
  - name : checkout
    uses : action/checkout@v4
  - name: Set up Docker
    uses: docker/setup-buildx-action@v3
  - name: Login to Docker Hub
    uses: docker/login-action@v3
    with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
  - name: Build and Push Docker Image
    uses: docker/build-push-action@v5
    with:
      context: ./app.py
      push: true
      tags: msujana/pyapp:latest
