name: Terraform

on:
  push:
    branches: [master]

jobs:
  terraform-deploy:
    name: EKS Run using Terraform
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.1.7"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Terraform Init
        run: terraform init
        working-directory: . 


      - name: Terraform Validate
        run: terraform validate
        working-directory: . 


      - name: Terraform Plan
        run: terraform plan -var-file="terraform.tfvars"
        working-directory: . 


      - name: Terraform Apply
        run: terraform apply -auto-approve -var-file="terraform.tfvars"
        working-directory: Mini_project

